spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=2
            - name: LoggingOrdersFilter
            - name: Authentication
              args:
                isEnabled: true
            - name: Authorization
              args:
                allowedRoles:
                  - ADMIN
                  - SUPER_ADMIN

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/v1/inventory/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=x-Custom-Header, Sush
            - name: Authentication
              args:
                isEnabled: true

jwt:
  secretKey: 03c674b5ec2576230b5b3b94a9fa1606720ccce6f1a617dadc0399559555ee8f // todo: store in env
