server:
  port: 9010
  servlet:
    context-path: /inventory

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:postgresql://${DB_SERVICE:inventory_DB}:5432/${DB_NAME:inventory_DB}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
     ddl-auto: create-drop
      # ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      
#   client:
#     service-url:
#       defaultZone: http://localhost:8761/eureka/ // this is define in global as application.yml
